import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Kanika',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Agrawal',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
      {
        name: 'Instant Items',
        category: 'Food',
        image: '/images/pic1.jpg',
        price: 354,
        countInStock: 10,
        brand: 'Amul',
        rating: 3.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Daily Essential Items',
        category: 'Food',
        image: '/images/pic2.jpg',
        price: 146,
        countInStock: 7,
        brand: 'MTR',
        rating: 2.5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        name: 'Fruits',
        category: 'Food',
        image: '/images/pic3.jpg',
        price: 87,
        countInStock: 3,
        brand: 'Natural',
        rating: 5,
        numReviews: 9,
        description: 'high quality product',
      },
      {
        name: 'Veggies',
        category: 'Food',
        image: '/images/pic4.jpg',
        price: 30,
        countInStock: 7,
        brand: 'Natural',
        rating: 4,
        numReviews: 7,
        description: 'high quality product',
      },
      {
        name: 'Energy Booster',
        category: 'Immunity Booster',
        image: '/images/pic5.jpg',
        price: 450,
        countInStock: 0,
        brand: 'Patanjali',
        rating: 2,
        numReviews: 6,
        description: 'high quality product',
      },
      {
        name: 'Eggs',
        category: 'Food',
        image: '/images/pic6.jpg',
        price: 50,
        countInStock: 100,
        brand: 'Natural',
        rating: 3.5,
        numReviews: 4,
        description: 'high quality product',
      },
      {
        name: 'Package Offer Available',
        category: 'Package Offer',
        image: '/images/pic7.jpg',
        price: 700,
        countInStock: 1,
        brand: 'Aashirwaad',
        rating: 5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Cereals',
        category: 'Minerals',
        image: '/images/pic8.jpg',
        price: 250,
        countInStock: 8,
        brand: 'Nestle',
        rating: 4,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        name: '3 Layer Face Mask',
        category: 'Covid Essentials',
        image: '/images/pic9.jpg',
        price: 5,
        countInStock: 100,
        brand: 'Vandelay',
        rating: 5,
        numReviews: 18,
        description: 'Breathable Material, Adjustable, for Single Use Only',
      },
      {
        name: 'Face Shield',
        category: 'Covid Essentials',
        image: '/images/pic10.jpeg',
        price: 25,
        countInStock: 50,
        brand: 'Steelbird',
        rating: 4,
        numReviews: 15,
        description: 'Static Full Face Protector For Each and Everyone',
      },
      {
        name: 'Hand Sanitizer',
        category: 'Covid Essentials',
        image: '/images/pic11.jpg',
        price: 67,
        countInStock: 20,
        brand: 'Dettol',
        rating: 5,
        numReviews: 23,
        description: 'Dettol Original Germ Protection Alcohol based Hand Sanitizer',
      },
      {
        name: 'Infrared Thermometer',
        category: 'Covid Essentials',
        image: '/images/pic12.jpg',
        price: 987,
        countInStock: 17,
        brand: 'Vandelay',
        rating: 4.5,
        numReviews: 23,
        description: 'Non Contact IR Thermometer, Forehead Temperature Gun',
      },
      {
        name: 'Thermometer',
        category: 'Covid Essentials',
        image: '/images/pic13.jpg',
        price: 299,
        countInStock: 10,
        brand: 'DOYO Remedies',
        rating: 5,
        numReviews: 12,
        description: 'Mercury Free with Rigid Tip',
      },
      {
        name: 'Pulse Oximeter',
        category: 'Covid Essentials',
        image: '/images/pic14.jpg',
        price: 800,
        countInStock: 21,
        brand: 'Dr.VAKU',
        rating: 4.5,
        numReviews: 54,
        description: 'Blood Oxygen Saturation Monitor Fingertip with Four Color TFT Screen',
      },
      {
        name: 'Disinfectant Spray',
        category: 'Covid Essentials',
        image: '/images/pic15.jpg',
        price: 318,
        countInStock: 8,
        brand: 'Dettol',
        rating: 4.5,
        numReviews: 8,
        description: 'Dettol Disinfectant Spray for Germ Protection on Hard & Soft Surfaces',
      },
      {
        name: 'First Aid Kit',
        category: 'Covid Essentials',
        image: '/images/pic16.jpg',
        price: 995,
        countInStock: 34,
        brand: 'Tool Zone',
        rating: 5,
        numReviews: 23,
        description: '64 Pcs of Medicines with Plastic Milton Box',
      },
      {
        name: 'Dabur Tulsi Drop',
        category: 'Herbal Products',
        image: '/images/pic17.jpg',
        price: 165,
        countInStock: 40,
        brand: 'Dabur',
        rating: 3.5,
        numReviews: 20,
        description: '100% Ayurvedic Immunity Booster, Cough & Cold Relief, 5 Tulsi Extracts, 20 ml (Get 10 ml Free)',
      },

      {
        name: 'Dabur Amla Ayurvedic Juice',
        category: 'Herbal Products',
        image: '/images/pic18.jpg',
        price: 206,
        countInStock: 50,
        brand: 'Dabur',
        rating: 4,
        numReviews: 29,
        description: 'Amla also is known as Indian Gooseberry is a rich source in Vitamin c, which helps boost immunity. ',
      },

      {
        name: 'Instant Ginger Drink',
        category: 'Herbal Products',
        image: '/images/pic19.jpg',
        price: 150,
        countInStock: 65,
        brand: 'Gold Kili',
        rating: 5,
        numReviews: 43,
        description: 'Instant Ginger Drink is made using top grade ginger and honey to give a refreshing feeling when consumed.',
      },

      {
        name: 'Khadi Herbal Products',
        category: 'Herbal Products',
        image: '/images/pic20.jpg',
        price: 120,
        countInStock: 76,
        brand: 'Khadi',
        rating: 4.5,
        numReviews: 40,
        description: 'Products are manufacturing with premium quality of herbs,packaging, & timely delivery with reputed transport services.120/uni',
      },



    ],
};
export default data;